name: Update Smartsheet WO Hyperlinks

on:
  repository_dispatch:
    types: [trigger-cron]
  workflow_dispatch:

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Execute Script
        env:
          SMARTSHEET_ACCESS_KEY: ${{ secrets.SMARTSHEET_ACCESS_KEY }}
          SMARTSHEET_SHEET_ID: ${{ secrets.SMARTSHEET_SHEET_ID }}
        run: python update_links.py
